Upgrade to Rails 5 2 and add fondation for test suite
parisrb/paris-rb.org pull request #177
Opened 2023-01-30 18:15 UTC by adrienpoly

- upgrades from Rails 5.0 to Rails 5.2
- add very basic test suite with example for model, controller and system test
- enhance seed with real world data. This is important as we will redesign the site to have realistic content both in development and for review apps with a simple task -> `rails db:reset` 
- add a very basic CI to run the test suite and ensure that we can always run `rails db:reset` (inspired by the [CI of RailsDevs](https://github.com/joemasilotti/railsdevs.com/blob/main/.github/workflows/ci.yml))

Next steps: 
- increase a bit the test coverage
- remove some dependencies that are not used
- upgrade to Rails 7
- upgrade to ruby 3.2

2023-01-30 18:54 UTC, adrienpoly commented
@btrd the preview fails can you let me know what is the error message ?

2023-01-30 19:02 UTC, ylecuyer commented
> @btrd the preview fails can you let me know what is the error message ?

Looks like the error is:

```
2023-01-30 19:53:03.371747999 +0100 CET [web-1] Puma starting in single mode...
2023-01-30 19:53:03.371799993 +0100 CET [web-1] * Puma version: 6.0.1 (ruby 2.7.7-p221) ("Sunflower")
2023-01-30 19:53:03.371801097 +0100 CET [web-1] * Min threads: 5
2023-01-30 19:53:03.371801468 +0100 CET [web-1] * Max threads: 5
2023-01-30 19:53:03.371802180 +0100 CET [web-1] * Environment: production
2023-01-30 19:53:03.371802549 +0100 CET [web-1] * PID: 15
2023-01-30 19:53:08.745738138 +0100 CET [web-1] bundler: failed to load command: puma (/app/vendor/bundle/ruby/2.7.0/bin/puma)
2023-01-30 19:53:08.745745936 +0100 CET [web-1] Errno::ENOENT: No such file or directory @ rb_sysopen - tmp/pids/server.pid
2023-01-30 19:53:08.745746717 +0100 CET [web-1] /app/vendor/bundle/ruby/2.7.0/gems/puma-6.0.1/lib/puma/launcher.rb:304:in `write'
2023-01-30 19:53:08.745747104 +0100 CET [web-1] /app/vendor/bundle/ruby/2.7.0/gems/puma-6.0.1/lib/puma/launcher.rb:304:in `write_pid'
2023-01-30 19:53:08.745808190 +0100 CET [web-1] /app/vendor/bundle/ruby/2.7.0/gems/puma-6.0.1/lib/puma/launcher.rb:112:in `write_state'
2023-01-30 19:53:08.746109007 +0100 CET [web-1] Did you mean? caller
2023-01-30 19:53:08.746216847 +0100 CET [web-1] /app/vendor/bundle/ruby/2.7.0/gems/puma-6.0.1/lib/puma/single.rb:48:in `run'
2023-01-30 19:53:08.746259010 +0100 CET [web-1] /app/vendor/bundle/ruby/2.7.0/gems/puma-6.0.1/lib/puma/launcher.rb:186:in `run'
2023-01-30 19:53:08.746260941 +0100 CET [web-1] /app/vendor/bundle/ruby/2.7.0/gems/puma-6.0.1/bin/puma:10:in `<top (required)>'
2023-01-30 19:53:08.746261748 +0100 CET [web-1] /app/vendor/bundle/ruby/2.7.0/bin/puma:23:in `<top (required)>'
2023-01-30 19:53:08.746261340 +0100 CET [web-1] /app/vendor/bundle/ruby/2.7.0/bin/puma:23:in `load'
2023-01-30 19:53:08.746260498 +0100 CET [web-1] /app/vendor/bundle/ruby/2.7.0/gems/puma-6.0.1/lib/puma/cli.rb:75:in `run'
```

2023-01-30 19:28 UTC, adrienpoly commented
ok preview works now 🎉, just missing the Sponsor logos....

2023-01-31 10:33 UTC, sunny requested changes
Géant ! 😍  

Le seul point bloquant est la méthode `send_slack_notification!`. Rien de bloquant dans le reste ce ne sont que des peaufinages.

2023-01-31 10:33 UTC, sunny commented on app/models/sponsor.rb
> +    # this is ugly, we will need to rename the column to starts_at, ends_at as unitl is a reserved word
```suggestion
    # This is ugly, we will need to rename the column to starts_at, ends_at as
    # `until` is a reserved word.
```

2023-01-31 10:33 UTC, sunny commented on app/models/sponsor.rb
> +  def active?
J’ai l’impression qu’on ne se sert pas de cette méthode.

2023-01-31 10:33 UTC, sunny commented on app/models/talk.rb
> +  def send_slack_notification!
Cette méthode mériterait d’être sortie des méthodes privées.

2023-01-31 10:33 UTC, sunny commented on config/application.rb
> +      g.test_framework  :test_unit, fixture: true
```suggestion
      g.test_framework :test_unit, fixture: true
```

2023-01-31 10:33 UTC, sunny commented on config/environments/development.rb
> +  if Rails.root.join('tmp', 'caching-dev.txt').exist?
Nul besoin de séparer les arguments ici, un `/` fonctionne très bien partout.

```suggestion
  if Rails.root.join('tmp/caching-dev.txt').exist?
```

2023-01-31 10:33 UTC, sunny commented on db/seeds.rb
> +Sponsor.all.delete_all
Au cas où on ait des dépendances.

```suggestion
Sponsor.all.destroy_all
```

2023-01-31 10:33 UTC, sunny commented on db/seeds.rb
> +sponsors = YAML.load(File.read("#{Rails.root}/test/fixtures/sponsors.yml")).values
Mini suggestions d’écriture un peu plus courte :

```suggestion
sponsors = YAML.load(Rails.root.join("test/fixtures/sponsors.yml").read).values
```

2023-01-31 10:33 UTC, sunny commented on db/seeds.rb
> +Video.all.delete_all
```suggestion
Video.all.destroy_all
```

2023-01-31 10:33 UTC, sunny commented on db/seeds.rb
> +videos = YAML.load(File.read("#{Rails.root}/test/fixtures/videos.yml")).values
```suggestion
videos = YAML.load(Rails.root.join("test/fixtures/videos.yml").read).values
```

2023-01-31 10:33 UTC, sunny commented on db/seeds.rb
> +Talk.all.delete_all
```suggestion
Talk.all.destroy_all
```

2023-01-31 10:33 UTC, sunny commented on db/seeds.rb
> +talks = YAML.load(File.read("#{Rails.root}/test/fixtures/talks.yml")).values
```suggestion
talks = YAML.load(Rails.root.join("test/fixtures/talks.yml").read).values
```

2023-01-31 10:33 UTC, sunny commented on db/seeds.rb
> +  talk.update_column(:happened_at, Time.current.to_date)
Pourquoi le transformer en date ici ? Si c'est pour avoir une date un peu dans le passé, pourquoi pas écrire `1.day.ago` ou encore

```suggestion
  talk.update_column(:happened_at, Time.current.at_midnight)
```

2023-01-31 10:33 UTC, sunny commented on test/test_helper.rb
> +
```suggestion
```

2023-01-31 10:33 UTC, sunny commented on test/system/home_page_test.rb
> +require "application_system_test_case"
On peut supprimer le fichier `test/system/.keep` vide vu que ce fichier existe.

2023-01-31 10:33 UTC, sunny commented on test/models/sponsor_test.rb
> +
```suggestion
```

2023-01-31 10:33 UTC, sunny commented on test/models/sponsor_test.rb
> +require 'test_helper'
On peut supprimer `test/models/.keep` vu que ce fichier existe.

2023-01-31 10:38 UTC, adrienpoly commented on .github/workflows/ci.yml
> +          bin/rails db:schema:load
on peut faire rails db:setup d'ailleurs non ?

2023-01-31 10:38 UTC, adrienpoly commented on app/models/talk.rb
> +  def send_slack_notification!
en effet

2023-01-31 10:39 UTC, adrienpoly commented on .github/workflows/ci.yml
> +          cp config/database.ci.yml config/database.yml
alors j'avais ça au début mais ça ne marchait pas du coup j'ai utilisé l'approche qui marche chez moi. je testerai again

2023-01-31 10:44 UTC, adrienpoly commented on db/seeds.rb
> +  talk.update_column(:happened_at, Time.current.to_date)
Alors en faite je crois que pour que le line up s'affiche après un reset de la db pendant une période suffisante (2 semaines) il faut faire

talk.update_column(:happened_at, 2.weeks.from_now)

2023-01-31 11:08 UTC, sunny commented on .github/workflows/ci.yml
> +          bin/rails db:schema:load
`setup` lance les seeds également

2023-01-31 17:05 UTC, sunny approved these changes
✨

2023-02-02 17:41 UTC, merged

2023-02-03 07:56 UTC, btrd commented
Merci !